### PR TITLE
Audit input-functions.md

### LINKED ISSUE #33: Audit and Fix `input-functions.md`
I'd like to work on `input-functions.md`, auditing it based on this checklist:

* Look for any typos
* Make sure all Markdown is correctly done.  The conversion was done automatically by a tool, so there may be more idiomatic ways to do some things
* Check the page in a Desktop browser.  Does it look OK?  Are there any issues that need to be fixed?
* Check the page in a Mobile browser.  Does it look OK?  Are there any issues that need to be fixed?
* Try the page in both Light and Dark mode.  Are there any issues that need to be fixed?
* Try running the page through Lighthouse: https://developers.google.com/web/tools/lighthouse.  Are there any issues that need to be fixed?
* Try running the page through Web Hint: https://webhint.io/.  Are there any issues that need to be fixed?
* Tables that are really wide (types.md) could be converted to use SVG or flex/grid. Make wide visual tables fit in the available viewport.  Another example is the table in `docs/D-Modularity/pointers.md`, where we should reduce the vertical padding/margins on tables. The tables are too large, and probably shouldn't be tables at all.
* Prefer Markdown tables vs. raw HTML tags
* Fix colours in tables so it uses global styles vs. inline styles
* Use alt tags for all images.  See https://supercooldesign.co.uk/blog/how-to-write-good-alt-text for suggestions
* Avoid blockquote for indentation, and prefer q or blockquote only when actually quoting.  Use Admonitions instead. Example: `docs/D-Modulatirty/pointers.md`: there are places where Blockquote are being used and Admonitions could replace it. “Note:” Lightbulb info Admonition.
* Make sure images work in dark and light modes.  For example, `docs/8-Computations/logic.md` Flags image is white background, needs to work in dark.  Create a “negative” or SVG so we can do Dark Mode?  Can we programmatically create this negative?
* Change colours for tables (don’t use Yellow).  We should use the default colour theme.
* Avoid using `<b>` and `<i>` to do emphasis.
* Use backticks and all code for memory addresses and such in tables that use things like void, int, function names, memory addresses.
* Make sure all code blocks use syntax highlighting
* centre images horizontally (esp. when they are small) so they work well at all responsive sizes
* check sub-script and super-script that they are correctly used in all cases
* consider including inter-site links to other pages that have related info
* all links should have descriptive text for accessibility
* Make sure that sub-headings (right-hand side) for each document are correct.
* Improve readability of code comments (i.e., `//` and `/*...*/`) in dark mode (even light mode might need some work)
* In places where `***...***` was used as a fourth heading level, use `####` instead.
* Fix Frontmatter for page to include proper id, title, slug, etc.

### PR DESCRIPTION
**Pull request by a-rokay**
This PR is an audit of `input-functions.md`:
 
* Add alt text to images 
* Encase key words in backticks
 * Add missing '-'
 * Remove extra indentation from code blocks
 * Add missing comma
 * Remove empty bullet point
 * Add title to frontmatter
 * Improve image centering
 * Add descriptive text to link
 * Add div.mdImg class for image centering

For the image centering, I went with the `text-align: center` approach which requires the image to be in a `div` tag. So I combined the existing `.mdImg` class with a `div.mdImg` class that does the centering. Because of this, I had to change the `span` tags in `functions.md` to `div` tags. Everything works as expected.

Let me know if I missed anything.

Fixes #33

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
In #46 we're adding the `ideal-image` plugin, which will do this image optimization and centering for us, cc @aserputov: can you confirm that I'm correct about this?

I think that we should probably switch to using this everywhere vs. doing our own styling.

**Comment by aserputov** [comment]
@a-rokay, that's great work you did here, but as @humphd mentioned above, it's probably better to use the Docusaurus internal plugin ```ideal image`` because it provides us with more optimized Images. (responsive, lazy-loading, and low-quality placeholder)[https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image]

**Comment by a-rokay** [comment]
Should I wait for #46 to be merged before continuing?

**Comment by humphd** [comment]
No, we can do it in #63, just leave a comment there.

**Comment by a-rokay** [comment]
I'm not sure what you want me to comment, just that `input-functions.md` requires ideal-image?

**Comment by humphd** [comment]
Yes, I don't want to lose track of knowledge, so we need to move unfinished work items forward into new or existing issues before we close things.

**Comment by a-rokay** [comment]
Got it, should I remove the image centering and CSS from this PR?

**Comment by humphd** [comment]
@a-rokay you can include it, but later we need to update all our uses of it.

**Comment by CameronGray1210** [comment]
Great Job many thanks!

**Pull request merged**
