### PR TITLE
converted EBCDIC collating sequence image into table

### PR DESCRIPTION
**Pull request by mkim219**
Issue #67 
 - converting EBCDIC collating sequence table image into Markdown table

### CODE REVIEW

**Comment by aserputov** [comment]
@mkim219 I did almost the same issue 😄 so yours looks good for me.

**Comment by aserputov** [comment]
@mkim219 looks even better now

**Comment by aserputov** [comment]
@mkim219 I have installed prettier locally. So each time I save file(ctrl+s) -> prettier formats it, maybe that's why mine looked different before.

**Review by CameronGray1210 — APPROVED** [review]
Great Job!

**Pull request merged**
