### PR TITLE
Added higher resolution icons

### PR DESCRIPTION
**Pull request by gusmccallum**

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
Amazing!

Do you want to run your 512x512 sized icon through https://app-manifest.firebaseapp.com/ and generate all the other sizes?  Different platforms need different sizes, see https://stackoverflow.com/questions/48839338/which-icon-sizes-are-required-for-progressive-web-apps-pwa-as-of-q1-2018

**Comment by Kevan-Y** [comment]
Review/Suggestion: 

@gusmccallum, Thanks for getting better quality icons. I suggest after getting all other sizes, you can add them to the `manifest.json` file.
https://github.com/Seneca-ICTOER/IPC144/blob/c622d7c365732ba923c60e6ec5b0f165e54a4586/static/manifest.json#L10
Also, update `docusaurus.config.js` according to the new size for smaller device.
https://github.com/Seneca-ICTOER/IPC144/blob/c622d7c365732ba923c60e6ec5b0f165e54a4586/docusaurus.config.js#L68

**Review by humphd — APPROVED** [review]

**Review by Kevan-Y — CHANGES_REQUESTED** [review]
Would it be better to have this new logo matching our favicon.ico?
@humphd

**Comment by humphd** [comment]
I stole Seneca's favicon from https://www.senecacollege.ca/home.html, so it's probably fine as is.

**Comment by humphd** [comment]
@Kevan-Y you good with this?  Can I merge, or is there more to do?

**Comment by Kevan-Y** [comment]
LGTM!

**Pull request merged**
