### PR TITLE
Fix and Audit `More Input and Output.md`

### LINKED ISSUE #82: Audit and fix `more-input-and-output.md`
Sub-issue of #18.
Auditing and fixing `more-input-and-output.md` based on the following tasks:

## Tasks
- [x]     Look for any typos
- [x]     Make sure all Markdown is correctly done. The conversion was done automatically by a tool, so there may be more idiomatic ways to do some things
- [x]     Check the page in a Desktop browser. Does it look OK? Are there any issues that need to be fixed?
- [x]     Check the page in a Mobile browser. Does it look OK? Are there any issues that need to be fixed?
- [x]     Try the page in both Light and Dark mode. Are there any issues that need to be fixed?
- [x]     Try running the page through Lighthouse: [https://developers.google.com/web/tools/lighthouse](https://developers.google.com/web/tools/lighthouse). Are there any issues that need to be fixed?
- [x]     Try running the page through Web Hint: [https://webhint.io](https://webhint.io/). Are there any issues that need to be fixed?
- [x]     Tables that are really wide (types.md) could be converted to use SVG or flex/grid. Make wide visual tables fit in the available viewport. Another example is the table in `docs/D-Modularity/pointers.md`, where we should reduce the vertical padding/margins on tables. The tables are too large, and probably shouldn't be tables at all.
- [x]     Prefer Markdown tables vs. raw HTML tags
- [x]     Fix colours in tables so it uses global styles vs. inline styles
- [x]     Use alt tags for all images. See https://supercooldesign.co.uk/blog/how-to-write-good-alt-text for suggestions
- [x]     Avoid blockquote for indentation, and prefer q or blockquote only when actually quoting. Use Admonitions instead. Example: `docs/D-Modulatirty/pointers.md`: there are places where > Blockquote are being used and Admonitions could replace it. “Note:” Lightbulb info Admonition.
- [x]     Make sure images work in dark and light modes. For example, `docs/8-Computations/logic.md` Flags image is white background, needs to work in dark. Create a “negative” or SVG so we can do Dark Mode? Can we programmatically create this negative?
- [x]     Change colours for tables (don’t use Yellow). We should use the default colour theme.
- [x]     Avoid using `<b>` and `<i>` to do emphasis.
- [x]     Use backticks and all code for memory addresses and such in tables that use things like void, int, function names, memory addresses.
- [x]     Make sure all code blocks use syntax highlighting
- [x]     centre images horizontally (esp. when they are small) so they work well at all responsive sizes
- [x]     check sub-script and super-script that they are correctly used in all cases
- [x]     consider including inter-site links to other pages that have related info
- [x]     all links should have descriptive text for accessibility
- [x]     Make sure that sub-headings (right-hand side) for each document are correct.
- [x]     Improve readability of code comments (i.e., `//` and `/*...*/`) in dark mode (even light mode might need some work)
- [x]     In places where `***...***` was used as a fourth heading level, use `####` instead.
- [x]     Fix Frontmatter for page to include proper id, title, slug, etc.

### PR DESCRIPTION
**Pull request by rclee91**
Fix #82 
Main changes are:
 - Fix typos
 - Add Frontmatter
 - Add inter-site links
 - Replace block quotes with admonitions
 - Add alt tag/descriptive text for links
 - Add backticks to code and memory addresses in tables
 - Replace `**...**` used as headings with heading level `####`

Other steps to check:
- Ran through [Lighthouse](https://developers.google.com/web/tools/lighthouse) and [Web Hint](https://webhint.io/))
- Checked light/dark modes in desktop and mobile

### CODE REVIEW

**Review by joshuali7536 — APPROVED** [review]
All the changes made look very good, formatting is much cleaner for code and tables, several typos were fixed, code keywords were highlighted properly, block-quotes updated, and several inline links were added. I also double checked on my end for light/dark and mobile views. All looks good!

**Review by roman-rezinkin — APPROVED** [review]
I really like the fact that you added the inter-site links to some of the paragraphs. That will greatly improve quality of life for users, as they can easily click on the link, without having to backtrack through the menu, trying to find the specific document. I noticed that you did a great job fixing the heading4, which was a good catch! On top of that the table looks great now. I think the changes LGTM, and the page looks a ton better than original.

**Review by MizuhoOkimoto — CHANGES_REQUESTED** [review]
Hi @rclee91! You did great work here! 
I just noticed a small thing. I think you can remove the comment below(red box):
image

Also, I was wondering if extra indentation inside the code block(Insufficient Memory) makes it hard to read on mobile like the image below:
image
It's just my suggestion. What do you think?

**Comment by rclee91** [comment]
> 
> 
> Hi @rclee91! You did great work here! I just noticed a small thing. I think you can remove the comment below(red box):
> 
> Also, I was wondering if extra indentation inside the code block(Insufficient Memory) makes it hard to read on mobile like the image below: It's just my suggestion. What do you think?

@MizuhoOkimoto 
Thanks for the review.

I took off the comment.

But the indents look consistent with all other code blocks on my end.

**Review by humphd — APPROVED** [review]

**Pull request merged**
