### PR TITLE
Add Weekly Schedule to footer

### PR DESCRIPTION
**Pull request by kiennguyenchi**
Solve Issue #54 

I added hyperlink of **Weekly Schedule** to the footer in *docusaurus.config.js*.
footer

I removed hyperlink of **Weekly Schedule** in **Contents** page in *docs/intro.md*.
content

### CODE REVIEW

**Comment by aserputov** [comment]
Why it looks like "prettier" didn't work ? I think it should be something like this>

              label: "Contents",
              to: "/",
            },
            {
              label: "Weekly Schedule",
              to: "/weeklyContents",
            },

**Comment by kiennguyenchi** [comment]
> Why it looks like "prettier" didn't work? I think it should be something like this >
> 
> ```
>           label: "Contents",
>           to: "/",
>         },
>         {
>           label: "Weekly Schedule",
>           to: "/weeklyContents",
>         },
> ```

So you mean that I should replace the single quotes with double quotes? We use single quotes in the entire file, so I think we should not.

**Comment by humphd** [comment]
We don't have prettier in the tree yet, see #50.

**Comment by aserputov** [comment]
@kiennguyenchi @humphd what I meant exactly is this ->
Screen Shot 2021-11-08 at 6 43 43 PM

**Comment by ycechungAI** [comment]
I have also tested this and nothing to change from above comments

**Comment by CameronGray1210** [comment]
Thanks - this makes sense and I'm sure will be used by many as another quick way to return to the weekly schedule.

**Pull request merged**
